name: Build and Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.6", "3.7", "3.8", "3.9", "3.10"]

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install -U pip setuptools wheel
        python -m pip install -U flake8 flake8-colors flake8-import-order
        python -m pip install -U pep8-naming pydocstyle pylint
        python -m pip install -U boto distro docopt pytest requests

    - name: Flake8 
      run: python -m flake8 
    - name: PyDocStyle
      run: python -m pydocstyle
    - name: PyLint
      run: python -m pylint wavefront_cli

    - name: Validate Version is Updated in __init__.py
      if: ${{ github.event_name == 'pull_request' }}
      run: test -n "$(git diff -G __version__ origin/master HEAD wavefront_cli/__init__.py)"

    - name: Test
      run: |
        pip install .
        wave -h
        pytest